---
- name: Cisco Backup Config
  hosts: "{{ host_group }}"
  connection: network_cli
  gather_facts: no

  tasks:

    - name: set intended config
      shell: cat /etc/configs/golden/{{inventory_hostname}}_golden.cfg
      register: golden_config

    - name: check the running-config against master config
      ios_config:
        diff_against: intended
        intended_config: "{{ golden_config.stdout }}"
      register: diff_against
